### ISSUE TITLE
Readme links need updated for new repo location

### ISSUE THREAD

**Issue by CreativeNotice** [teamcfadvance/cfstatic#112]

**Comment by DannyCork** [comment]
closed and merged pull request automatically (by accident!)

**Comment by deanlaw** [comment]
Should this update also be added to the development branch? Also, for my own clarification, should we be working on these issues in the development branch first and then merge them with the master branch? Sorry if the question sounds ignorant, but I just want to make sure that when I am able to contribute, that I am following the right workflow.

**Comment by CreativeNotice** [comment]
Dean, I think that's up to you. It would be interesting to work in http://semver.org/. Perhaps non-breaking bug fixes and features are pulled right into master but breaking features are released in another branch (maybe dev) for review before being merged to master.
