### ISSUE TITLE
Transfer RIAForge project page to TeamCFAdvance

### ISSUE THREAD

**Issue by CreativeNotice** [teamcfadvance/cfstatic#114]

**Comment by CreativeNotice** [comment]
Taking this one. Contacted Raymond and Dominic to facilitate the project transfer to our account.

**Comment by DannyCork** [comment]
Does the below close this issue?

Raymond has finished the project move on RIAForge for us. I've updated the description and links.
http://cfstatic.riaforge.org/

Thanks everyone involved, was an awesomely easy project move.

Ryan

**Comment by CreativeNotice** [comment]
It does. I forgot to close the issue!
